### ISSUE TITLE
作者你好，想请教一下

### ISSUE THREAD

**Issue by freesnowmountain** [BlinkDL/RWKV-CUDA#7]
作者你好，我们复现了您的代码，发现使用cuda确实可以实现很大程度的加速。我们目前在研究如何使用cuda加速Unet网络从而解决一些问题，想请教您一些有关cuda的问题。并且如果您了解之后，对我们感兴趣的话，我们想与您合作做一些研究。如果您觉得可以的话，请回复我。 @BlinkDL

**Comment by BlinkDL** [comment]
我也是cuda新手，可以加QQ群325154699
